@echo off
setlocal EnableDelayedExpansion

echo.
echo ========================================
echo   PROJECT MANAGEMENT - COMPLETE SETUP
echo ========================================
echo.
echo This script will:
echo   1. Check your Netlify connection
echo   2. Get DATABASE_URL from Netlify
echo   3. Generate JWT_SECRET
echo   4. Create .env file
echo   5. Run database migrations
echo   6. Deploy to production
echo.
echo Press any key to start...
pause >nul
cls

echo.
echo ========================================
echo   Step 1: Checking Netlify CLI
echo ========================================
echo.

where netlify >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Netlify CLI not installed!
    echo.
    echo Installing Netlify CLI...
    call npm install -g netlify-cli
    if !errorlevel! neq 0 (
        echo ERROR: Failed to install Netlify CLI
        pause
        exit /b 1
    )
)
echo ✓ Netlify CLI ready

echo.
echo ========================================
echo   Step 2: Getting Environment Variables
echo ========================================
echo.

echo Fetching from Netlify...
netlify env:list > temp_env.txt 2>&1

findstr "DATABASE_URL" temp_env.txt >nul
if errorlevel 1 (
    echo.
    echo ERROR: DATABASE_URL not found in Netlify!
    echo.
    echo Please:
    echo 1. Go to https://app.netlify.com
    echo 2. Select your site
    echo 3. Integrations -^> Enable Neon Database
    echo 4. Wait for DATABASE_URL to be added
    echo 5. Then run this script again
    echo.
    del temp_env.txt
    pause
    exit /b 1
)

for /f "tokens=2 delims=│" %%a in ('findstr "DATABASE_URL" temp_env.txt') do (
    set "db_url=%%a"
    set "db_url=!db_url:~1,-1!"
)
del temp_env.txt

if "!db_url!"=="" (
    echo ERROR: Could not extract DATABASE_URL
    echo.
    echo Please manually:
    echo 1. Run: netlify env:list
    echo 2. Copy DATABASE_URL value
    echo 3. Run: setup-env.bat
    echo.
    pause
    exit /b 1
)

echo ✓ DATABASE_URL found

echo.
echo ========================================
echo   Step 3: Generating JWT_SECRET
echo ========================================
echo.

set "jwt_secret=JWT_%RANDOM%%RANDOM%%RANDOM%%RANDOM%%RANDOM%%RANDOM%_SECRET"
echo ✓ JWT_SECRET generated: !jwt_secret!

echo.
echo ========================================
echo   Step 4: Creating .env File
echo ========================================
echo.

(
echo # Auto-generated by complete-setup.bat
echo DATABASE_URL=!db_url!
echo JWT_SECRET=!jwt_secret!
echo TELEGRAM_BOT_TOKEN=8285823339:AAFf0YQF1WzkOW2mm2NzSzpEI67sJafn42o
echo.
echo # TELEGRAM_CHAT_ID is optional - users set it in Profile Settings
echo TELEGRAM_CHAT_ID=
) > .env

echo ✓ .env file created

echo.
echo ========================================
echo   Step 5: Adding JWT_SECRET to Netlify
echo ========================================
echo.

echo Adding to Netlify environment...
netlify env:set JWT_SECRET "!jwt_secret!" >nul 2>&1
if errorlevel 1 (
    echo WARNING: Could not auto-add JWT_SECRET to Netlify
    echo.
    echo Please manually add:
    echo 1. Go to https://app.netlify.com
    echo 2. Your site -^> Site settings -^> Environment variables
    echo 3. Add variable:
    echo    Key: JWT_SECRET
    echo    Value: !jwt_secret!
    echo.
    echo Press any key after adding it...
    pause >nul
) else (
    echo ✓ JWT_SECRET added to Netlify
)

echo.
echo ========================================
echo   Step 6: Installing Dependencies
echo ========================================
echo.

if not exist node_modules (
    echo Installing packages...
    call npm install
    if errorlevel 1 (
        echo ERROR: npm install failed
        pause
        exit /b 1
    )
)
echo ✓ Dependencies installed

echo.
echo ========================================
echo   Step 7: Generating Migrations
echo ========================================
echo.

call npm run db:generate
if errorlevel 1 (
    echo ERROR: Failed to generate migrations
    echo.
    echo Check:
    echo - DATABASE_URL is correct
    echo - Neon database is active
    echo.
    pause
    exit /b 1
)
echo ✓ Migrations generated

echo.
echo ========================================
echo   Step 8: Running Migrations
echo ========================================
echo.

call npm run db:migrate
if errorlevel 1 (
    echo ERROR: Failed to run migrations
    echo.
    echo This might be okay if tables already exist.
    echo Do you want to continue with deployment? (Y/N)
    set /p continue=
    if /i "!continue!" neq "Y" (
        exit /b 1
    )
) else (
    echo ✓ Migrations applied
)

echo.
echo ========================================
echo   Step 9: Deploying to Production
echo ========================================
echo.

call netlify deploy --prod
if errorlevel 1 (
    echo ERROR: Deployment failed
    echo.
    echo Check:
    echo - Build logs above for errors
    echo - Netlify dashboard for issues
    echo.
    pause
    exit /b 1
)

echo.
echo ========================================
echo   ✓✓✓ SUCCESS! ✓✓✓
echo ========================================
echo.
echo Your application is now LIVE!
echo.
echo Opening your site...
timeout /t 2 >nul
call netlify open:site
echo.
echo ========================================
echo   NEXT STEPS:
echo ========================================
echo.
echo 1. Register your account on the site
echo 2. Login to the application
echo 3. Go to Settings page
echo 4. Get your Telegram Chat ID:
echo    - Message @userinfobot on Telegram
echo    - Copy your Chat ID
echo 5. Paste it in Settings -^> Telegram Chat ID
echo 6. Save and start using!
echo.
echo ========================================
echo   Your Credentials (Save these):
echo ========================================
echo.
echo Site URL: [Check browser]
echo JWT_SECRET: !jwt_secret!
echo DATABASE_URL: [Saved in .env]
echo.
echo IMPORTANT: Save JWT_SECRET somewhere safe!
echo.
pause

endlocal
